### ISSUE TITLE
Request for the cleaned version of the dataset

### ISSUE THREAD

**Issue by shashank6** [lsy3/clinical-notes-diagnosis-dl-nlp#1]
Hello,

I am trying to replicate the project. I am following the procedure in README and you said that there is a google drive link which contains the cleaned version of the dataset. I searched for a link in Environment Setup(Local) and couldn't find it. It would be great if you can share the cleaned version of the dataset.

Regards,
Shashank.

**Comment by lsy3** [comment]
Added!
