### ISSUE TITLE
Error in preprocessing stage

### ISSUE THREAD

**Issue by shashank6** [lsy3/clinical-notes-diagnosis-dl-nlp#2]
Hello,

Thanks for the soon reply last time.

I have been compiling your code by following the README but I am getting a few error in the preprocess.py

Line 54 : It say didn't use the function properly and can you tell me the use of that line in RDD ?
Line 152: It says the filter is not defined properly. Can you explain me the line 151 and 152 ?
Line 198: It says unhashable type : set (Type Error)

I think there is some relation between the set() used in Line 151 and the error displayed in Line 198  and maybe the type in the sparse2vec function is not matching or not able to cast it with the main function.

Thanks in advance.

Regards,
Shashank Reddy Boosi.

**Comment by lsy3** [comment]
1. read the python notebook. It has more information/hints on what things do
2. if my memory serves me correctly
- line 54 makes an RDD of icd <-> smallest hadm_id (in the data, there are icd <-> a LOT of hadm_id)
- line 152 makes an RDD Of id <-> top X icd 9 code. (in the data, there are icd <-> a LOT of icd 9 code)
- line 198: not really sure. sparse2vec should return an array of 1s or 0s that tells if the hadm_id has that icd9 code (flag as 1).

**Comment by shashank6** [comment]
Thanks for the insights, as I modified the codes accordingly.

Regards,
Shashank Reddy Boosi.
