### ISSUE TITLE
Word2Vec - Feature Extraction Issue

### ISSUE THREAD

**Issue by shashankboosi** [lsy3/clinical-notes-diagnosis-dl-nlp#3]
Hello there,

I have three queries regarding the inputs to the feature extraction step:

1)Can you tell me from where did you get the bin file stated under

> bio_nlp_vec/PubMed-shuffle-win-*.txt Download here (you will need to convert the .bin files to .txt. I used gensim to do this)

Because I have many sh files in it. I didn't understand how you got the bin file because in the Bio_NLP they showed the procedure for

> pre-process.sh: segment and tokenized input text (e.g. raw PubMed or PMC text) 
> create_shf_low_text.sh: create lowercased and sentence-shuffled text (input: tokenized text) 
> createModel.sh: Create word2vec.bin file with different parameters 
> intrinsicEva.sh: run intrinsic evaluation on UMNSRS and Mayo data-set (input: Dir. for testing vector) 
> ExtrinsicEva.sh: run extrinsic evaluation 

In the createModel.sh they say they got the bin file. So is that the bin file you are talking about or else should I execute anything else to get the PubMed-shuffle-win-*.txt

2)I searched for the 

> model_word2vec_v2_*dim.txt (generated word2vec) 

and 

> model_doc2vec_v2_*dim_final.csv (generated word2vec)

  that are used in the feature extraction ipython notebooks . So I checked the generators and found the doc2vec but I am not able to find the word2vec text file.

3) I have a doubt from which file you extracted the 

> TRAIN-VAL-TEST-HADMID.p

 pickle file which is used as an input in the feature extraction non-seq notebook and what does that pickle file contain ?

Thanks in advance.

Regards,
Shashank Reddy Boosi.

**Comment by lsy3** [comment]
1. In [bionlp repo](https://github.com/cambridgeltl/BioNLP-2016), they have a gdrive [link](https://drive.google.com/open?id=0BzMCqpcgEJgiUWs0ZnU0NlFTam8) for the word vector.
2. The word2vec model generator is in "code/word2vec-generator.ipynb".
3. It literally just contains the train, validation, and test hadmid just to my partitioning is consistent between runs/computer. Refer to the Helper function separate_2 in "code/feature_extraction_nonseq.ipynb" on how to read it.
